---
- name: Remove legacy packages
  block:

    - name: Remove legacy packages
      ansible.builtin.apt:
        name: "{{ legacy_packages }}"
        state: absent
        purge: true

  rescue:
    - name: Show failure message but keep going
      ansible.builtin.debug:
        msg: "WARNING: pkg_remove_legacy failed on {{ inventory_hostname }}, check manually. Rest of playbook will continue."