##encrypt the inventory with vault so password on inventory is safe and add on .gitignore too 
[prod]
test ansible_host=10.0.0.99 ansible_connection=ssh ansible_user=amrit ansible_become_password="XXXXX" ansible_ssh_pass="XXXXX"
