---
- name: Apply Linux hardening
  hosts: all
  become: true

  roles:
    - role: pkg_remove_legacy
      tags:
        - pkg_remove_legacy

    - role: pkg_unattended_upgrades
      tags:
        - pkg_unattended_upgrades

    - role: pkg_kernel_module_blacklist
      tags:
        - pkg_kernel_module_blacklist


